filebeat.inputs:
  - type: container
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - decode_json_fields:
          fields: ["message"]
          target: "json"
          overwrite_keys: true

  # 🔵 Blue Team logs (PowerShell)
  - type: log
    enabled: true
    paths:
      - '/blue-team-logs/blue-team.log'   # <<<<<< ruta corregida
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      fileset.name: "blue-team"
      script: "blue-team-traffic"
    fields_under_root: true

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "changeme"

setup.kibana:
  host: "http://kibana:5601"
  username: "elastic"
  password: "changeme"

setup.dashboards.enabled: true

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
